### ISSUE TITLE
[Feature request] Customising commands

### ISSUE THREAD

**Issue by PivitParkour94** [psliwa/idea-composer-plugin#55] opened 2018-01-04 00:45 UTC
Hey, First of all, this plugin is great. Thank you!

It would be really cool thought if there was a way to use the composer commands with custom arguments passed in, for example, maybe in the Tools -> Composer menu have {{create custom command}} which would bring up a form much like the Edit Run Configuration's menu. I understand this increases scope significantly (validating inputs, saving custom data, not corrupting items) but it would be awesome if you are still developing :)

I'd be happy to help contribute with bringing this to fruition (I just have to learn how to develop for idea plugins first, but how hard could that be? ;])

Cheers Dude

**Comment by PivitParkour94** [comment] 2018-01-04 00:46
Wow it is easy to close an issue. Woops.

**Comment by psliwa** [comment] 2018-01-04 22:09
Hi, I think this issue is probably the same as https://github.com/psliwa/idea-composer-plugin/issues/54. I will add this feature soon.

**Comment by psliwa** [comment] 2018-01-08 21:16
I am closing this issue because it is duplicate of #54 - I am working right now on this feature.

**Closed by psliwa** 2018-01-08 21:16 UTC
