### ISSUE TITLE
java.lang.Throwable: Icon cannot be found in 'icons/packagist.png'

### ISSUE THREAD

**Issue by cedricziel** [psliwa/idea-composer-plugin#64] opened 2018-06-15 07:38 UTC
Error with the current EAP of IntelliJ:

```
IntelliJ IDEA 2018.2 EAP (Ultimate Edition)
Build #IU-182.3208.16, built on June 14, 2018
IntelliJ IDEA EAP User
Expiration date: July 14, 2018
JRE: 1.8.0_152-release-1226-b7 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-23-generic
```

<details>
<summary>`java.lang.Throwable: Icon cannot be found in 'icons/packagist.png', aClass='class org.psliwa.idea.composerJson.Icons$'`</summary>

```
java.lang.Throwable: Icon cannot be found in 'icons/packagist.png', aClass='class org.psliwa.idea.composerJson.Icons$'
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:123)
	at com.intellij.openapi.util.IconLoader.getIcon(IconLoader.java:148)
	at com.intellij.openapi.util.IconLoader.getIcon(IconLoader.java:109)
	at org.psliwa.idea.composerJson.Icons$.<init>(Icons.scala:9)
	at org.psliwa.idea.composerJson.Icons$.<clinit>(Icons.scala)
	at org.psliwa.idea.composerJson.intellij.filetype.ComposerJsonFileType.getIcon(ComposerJsonFileType.scala:14)
	at com.intellij.psi.impl.ElementBase.getBaseIcon(ElementBase.java:132)
	at com.intellij.psi.impl.ElementBase.computeBaseIcon(ElementBase.java:115)
	at com.intellij.psi.impl.ElementBase.lambda$computeIcon$1(ElementBase.java:93)
	at com.intellij.util.AstLoadingFilter.disableTreeLoading(AstLoadingFilter.java:126)
	at com.intellij.util.AstLoadingFilter.disableTreeLoading(AstLoadingFilter.java:115)
	at com.intellij.psi.impl.ElementBase.computeIcon(ElementBase.java:93)
	at com.intellij.psi.impl.ElementBase.getIcon(ElementBase.java:74)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.lambda$update$0(AbstractPsiBasedNode.java:137)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:915)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.update(AbstractPsiBasedNode.java:126)
	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.getUpdatedPresentation(PresentableNodeDescriptor.java:88)
	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.update(PresentableNodeDescriptor.java:41)
	at com.intellij.ui.tree.StructureTreeModel$Node.update(StructureTreeModel.java:280)
	at com.intellij.ui.tree.StructureTreeModel$Node.<init>(StructureTreeModel.java:262)
	at com.intellij.ui.tree.StructureTreeModel$Node.<init>(StructureTreeModel.java:256)
	at com.intellij.ui.tree.StructureTreeModel.getValidChildren(StructureTreeModel.java:235)
	at com.intellij.ui.tree.StructureTreeModel.getNode(StructureTreeModel.java:139)
	at com.intellij.ui.tree.StructureTreeModel.isLeaf(StructureTreeModel.java:175)
	at com.intellij.ui.tree.AsyncTreeModel$CmdGetChildren.load(AsyncTreeModel.java:575)
	at com.intellij.ui.tree.AsyncTreeModel$CmdGetChildren.getNode(AsyncTreeModel.java:550)
	at com.intellij.ui.tree.AsyncTreeModel$ObsolescentCommand.get(AsyncTreeModel.java:442)
	at com.intellij.ui.tree.AsyncTreeModel$ObsolescentCommand.get(AsyncTreeModel.java:408)
	at com.intellij.util.concurrency.Command$Processor.lambda$process$1(Command.java:48)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1151)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:84)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:137)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:126)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:84)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:105)
	at com.intellij.util.concurrency.Invoker.invokeSafely(Invoker.java:114)
	at com.intellij.util.concurrency.Invoker.lambda$invokeLater$0(Invoker.java:76)
	at com.intellij.util.concurrency.Invoker$BackgroundThread.lambda$offer$0(Invoker.java:248)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2$1.run(BoundedTaskExecutor.java:212)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:229)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:205)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

</summary>

**Comment by b1rdex** [comment] 2018-06-18 01:35
Same here in PhpStorm EAP

Plus this:
```
java.lang.NoClassDefFoundError: Could not initialize class org.psliwa.idea.composerJson.Icons$
	at org.psliwa.idea.composerJson.intellij.filetype.ComposerJsonFileType.getIcon(ComposerJsonFileType.scala:14)
	at com.intellij.psi.impl.ElementBase.getBaseIcon(ElementBase.java:132)
	at com.intellij.psi.impl.ElementBase.computeBaseIcon(ElementBase.java:115)
	at com.intellij.psi.impl.ElementBase.lambda$computeIcon$1(ElementBase.java:93)
	at com.intellij.util.AstLoadingFilter.disableTreeLoading(AstLoadingFilter.java:126)
	at com.intellij.util.AstLoadingFilter.disableTreeLoading(AstLoadingFilter.java:115)
	at com.intellij.psi.impl.ElementBase.computeIcon(ElementBase.java:93)
	at com.intellij.psi.impl.ElementBase.getIcon(ElementBase.java:74)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.a(AbstractPsiBasedNode.java:137)
…
```

**Comment by b1rdex** [comment] 2018-06-18 01:36
Oh, this is duplicate of #61

**Comment by psliwa** [comment] 2018-06-20 17:31
#61 duplicate.

**Closed by psliwa** 2018-06-20 17:31 UTC
